spring.application.name=coding_tracker

spring.datasource.url=jdbc:postgresql://localhost:5432/coding_tracker
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:default_local_password}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.secret-key=${JWT_SECRET:default_unsecure_key_that_is_long_enough_to_not_crash}
app.jwt-expiration=${JWT_EXPIRATION:86400000}

# Show all debug logs for the security package
logging.level.com.abi.coding_tracker.security=DEBUG


#management endpoint configuration
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
